### PR TITLE
TwitterBot

### LINKED ISSUE #554: Create LoggedActions for TwitterBot
TwitterBot does things like removing data, but it's hard to see what it's doing.

For example, it removed data from this profile wrongly:

https://candidates.democracyclub.org.uk/person/48988

We should create a `LoggedAction` for each edit it does. 

Bots are people too.

h/t @sjorford

### PR DESCRIPTION
**Pull request by symroe**
Closes #554

Need to manually create a user called `TwitterBot` before deploying this. I'm reluctant to use `get_or_create` here in case the username is already taken.  I'm not sure either is ideal, but the existing bots assume the username is reserved for them, so this is consistent at least.

### CODE REVIEW

**Comment by symroe** [comment]
This results in some noise in the recent changes feed, but I think it's helpful: 

screenshot 2018-08-13 14 48 39

**Comment by chris48s** [comment]
> Need to manually create a user called `TwitterBot` before deploying this. I'm reluctant to use `get_or_create`

I haven't read the whole code over, but if we need a user called `TwitterBot` in the DB for this to work (including on local dev installs), that seems like a good case for creating the relevant user object in a data migration in this PR.

**Comment by symroe** [comment]
Tests were failing on a test for a feature I _had no idea existed_. 🎉

**Comment by symroe** [comment]
Yeah, I think this `extra` method is better than what I did there. Might be worth going back and changing it.

**Pull request merged**
