### PR TITLE
SoPN import updates

### PR DESCRIPTION
**Pull request by symroe**
* Clean up the management command a little
* Add celery task for parsing SoPNs after import

### CODE REVIEW

**Comment by symroe** [comment]
This pull request **fixes 1 alert** when merging 37d686c1fbd55ef157f702f490f6d84d41da85c6 into f6787b1653f4482410ffd3d9d9dcfe85c349bf38 - [view on LGTM.com](https://lgtm.com/projects/g/DemocracyClub/yournextrepresentative/rev/pr-d21124748a4c9e0ae32ea45c8d09aec2c4990cf0)

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by chris48s** [comment]
The other things that might be useful to do here:

* Add a setting to `local.example.py` that will make this work in local dev
* If there's a very easy way to get visibility on the worker queue via `/admin`, we could usefully add it

**Comment by symroe** [comment]
Screenshot 2019-04-03 16 27 58

We'll see how useful this is, but it's a start

**Comment by symroe** [comment]
This pull request **fixes 1 alert** when merging 7a8189f1fbf6fcd19b8b41fa980693fd0ce77e00 into 548d6b11d2f9828498043e88f59c7c61f4db70a8 - [view on LGTM.com](https://lgtm.com/projects/g/DemocracyClub/yournextrepresentative/rev/pr-7b0afc44f298390fa27741ca0bd06880a13cca54)

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by symroe** [comment]
This pull request **fixes 2 alerts** when merging e7ea5e9d1c8b4ff8e462842ded3d9aa834e7b5a7 into 548d6b11d2f9828498043e88f59c7c61f4db70a8 - [view on LGTM.com](https://lgtm.com/projects/g/DemocracyClub/yournextrepresentative/rev/pr-9b21547b7eea3c2ba8a64ad14faa623910145bc7)

**fixed alerts:**

* 1 for Except block handles &#39;BaseException&#39;
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
