### PR TITLE
Fix sentence

### PR DESCRIPTION
**Pull request by hugovk**
"Download of the all candidates" is a little clunky.

https://candidates.democracyclub.org.uk/help/api#csv

---

image

### CODE REVIEW

**Comment by andylolz** [comment]
Being super duper pernickety: for consistency, I wonder if this should be “Download *of* all the candidates”?

**Comment by hugovk** [comment]
I thought of that first, but it's still a little needlessly clunky. 

Thinking further, and for consistency, the others would be improved as "Download the X candidates".

**Comment by andylolz** [comment]
I’d be happy with that! :)

**Comment by andylolz** [comment]
Sounds good!

**Comment by hugovk** [comment]
Updated!

**Comment by andylolz** [comment]
Cool! But note that this test needs updating to match:
https://github.com/DemocracyClub/yournextrepresentative/blob/master/candidates/tests/test_api_help_view.py#L22

(sorry about this!)

**Comment by hugovk** [comment]
There we go!

**Comment by andylolz** [comment]
Looks good to me 👍

**Pull request merged**
