### PR TITLE
Improve sopn parsing party matching

### PR DESCRIPTION
**Pull request by symroe**
This change does a couple of things:

1. Makes independant matching a little better, meaning we should avoid matching "Independent Dickens Heath Residents Action Group" when the party is "Independant" 
2. Uses "Levenshtein" distance queries before "starts with" queries, to avoid matching longer descriptions that happen to start with the search text. 

Hopefully this will prevent a couple of the most common problems with SOPN parsing

### CODE REVIEW

**Comment by VirginiaDooley** [comment]
I've tried this with `local.runnymede.chertsey-st-anns.2022-05-05`. The extraction data is 100% but the matching for the form ("add candidates from nom paper") did not work at all.

**Review by VirginiaDooley — COMMENTED** [review]
I've tried this with `local.runnymede.chertsey-st-anns.2022-05-05`. The extraction data with both Textract and Camelot is 100% coverage but the matching for the form ("add candidates from nom paper") did not work at all.

**Comment by symroe** [comment]
Just checking, did you run `parse_tables` on the extracted data? Was there a `raw_data` object in the database?

**Comment by VirginiaDooley** [comment]
Unrelated to this but related to SOPN, the click to add file feature only works with two attempts on my machine. Not a big deal but FYI in case it comes up later.

**Review by VirginiaDooley — APPROVED** [review]
Test with https://candidates.democracyclub.org.uk/elections/local.mansfield.west-bank.by.2024-06-20/sopn and nailed it 🎯

Screenshot 2024-06-07 at 9 28 59 AM

**Pull request merged**
