### PR TITLE
Add missing comma in management command

### PR DESCRIPTION
**Pull request by andylolz**

### CODE REVIEW

**Comment by symroe** [comment]
Thanks, but I think this is a borked merge – the 2nd line should be removed all together.  No idea how this crept in :/

**Comment by andylolz** [comment]
> I think this is a borked merge

I suspect this has been caused by force pushing to `master`?

**Comment by symroe** [comment]
Yeah, I just rebased over a fixup to f8d2206918f90f13c4a9ff146584460ebed3a553 and force pushed – that commit was the one that merged badly in the past somehow

**Comment by andylolz** [comment]
Okay… Looks like that has fixed this.

**Pull request closed without merging**
