### PR TITLE
Add candidate result rank where rank is None

### PR DESCRIPTION
**Pull request by VirginiaDooley**
Ref https://github.com/DemocracyClub/yournextrepresentative/issues/2173

I tested this migration by updating `num_ballots` in the db (rather than in the form where the rank would be automatically set) then running the migration to set rank where it had previously been set to `None`. Rank was updated as expected. 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206089991942155

### CODE REVIEW

**Comment by symroe** [comment]
Can you double check that this is doing the right thing? I can't really follow how the code can update the rank according to each candidate's position to other candidates on that ballot. It looks like the rank it set to one more than the number of candidates across the whole database where the number of votes is greater?

**Comment by VirginiaDooley** [comment]
@GeoWill I've added a fixup commit (which maybe should be a separate migration?) to achieve what we discussed. Instead of taking the full list of candidate results and ranking them, this change updates rank based on a given result set which is attached to a ballot. Lmk what you think.

**Comment by GeoWill** [comment]
Looks much more likely to me. I don't have the YNR data model in my head properly, so would find it easiest to just see it in action.

**Comment by VirginiaDooley** [comment]
> Looks much more likely to me. I don't have the YNR data model in my head properly, so would find it easiest to just see it in action.
I'm not aware of a way to import candidate results, so I'm testing with a small sample set. That said, I did create a set for more than one ballot and it updated rank for each as hoped. That said, it's possible there is a better way to achieve the same result.

**Comment by VirginiaDooley** [comment]
> > Looks much more likely to me. I don't have the YNR data model in my head properly, so would find it easiest to just see it in action.
> 
> I'm not aware of a way to import candidate results, so I'm testing with a small sample set. That said, I did create a set for more than one ballot and it updated rank for each as hoped. That said, it's possible there is a better way to achieve the same result.

@symroe I think you mentioned a db dump I could use to test this with a wider dataset?

**Review by symroe — APPROVED** [review]

**Pull request merged**
