### PR TITLE
Move person to people app

### PR DESCRIPTION
**Pull request by symroe**
Here's another huge PR, sorry. 

In scope:

* Moving existing code and data to a new app

Out of scope:

* Changing anything else, as much as that's possible

For example, the Person model is _huge_ and needs thinking about, but not here or now.

The only exception to this rule is in e1d98c6, where I've disabled some signals and tests. Let's chat about this.

### CODE REVIEW

**Comment by symroe** [comment]
[Move Person model to People app](https://trello.com/c/okGbNLs9/1512-move-person-model-to-people-app)

**Comment by chris48s** [comment]
Difficult to leave an inline comment but now that you've moved PersonQuerySet to `ynr/apps/people/managers.py` you can delete it from `ynr/apps/popolo/querysets.py`. You also don't need to import it in `ynr/apps/popolo/models.py`.

Apart from that, I reckon its probably good to go.

> I've disabled some signals and tests. Let's chat about this.

Ok. Give me a shout on slack then :)

**Comment by chris48s** [comment]
As well as removing the import, can't we remove the actual code: https://github.com/DemocracyClub/yournextrepresentative/blob/move_person_to_people_app/ynr/apps/popolo/querysets.py#L64

or is there a reason to duplicate `PersonQuerySet` in 2 places?

**Comment by symroe** [comment]
Good catch, thanks. Deleted it in `popolo` and cleaned up the imports 👍 

As per Slack, I'm going to delete the signal and tests. It's not so complex we can't add it back later if we want to

**Pull request merged**
