### PR TITLE
Add django's media context processor

### LINKED ISSUE #426: all the CSV links are dead
https://candidates.democracyclub.org.uk/help/api

e.g:
https://candidates.democracyclub.org.uk/help/candidates-local.arun.2018-02-22.csv
https://candidates.democracyclub.org.uk/help/candidates-naw.c.2018-02-06.csv

### PR DESCRIPTION
**Pull request by symroe**
This allows MEDIA_ROOT to be used in tempaltes. It was active in the
past but looks like it was missed in the move to the new settings and
template dict.

Closes #426 and replaces the fix in #428

### CODE REVIEW

**Comment by symroe** [comment]
Looks like this was lost due to not extending the global context processors:

https://github.com/DemocracyClub/yournextrepresentative/blob/25c1c6329b28c0698877eacb60b655355bd5a35c/mysite/settings/conf.py#L210

I've just amended this PR to include all default context processors lost in the move.

**Comment by chris48s** [comment]
Sorted 👍 

I'm slightly confused about whether [this](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/context_processors.py#L30) is actually... pointful, but a bit cruft is probably the least of our worries here.

When deploying this fix, the other major thing is https://github.com/DemocracyClub/YNR_deploy/pull/6

**Comment by chris48s** [comment]
Before merging this, I'm just going to run the py 2.7 build again. I think it is a transient/unrelated failure, but I'd like to check..

**Comment by symroe** [comment]
Good catch - I reckon that line is not pointful at all

**Pull request merged**
