### PR TITLE
Sopn parsing debug

### PR DESCRIPTION
**Pull request by michaeljcollinsuk**
- Migration to store empty relevant_pages as an empty string rather than `None`, to help with issue where we were getting lots of debug prints trying to extract tables on documents that we have not been able to store relevant_pages from 
- Adds more prints to try to help see where parsing is failing.
- Change how we drop rows from the parsed tables - increases number of people parsed to 279
- Improve shell output to make it easier to spot when parsing changes
- Dont write a new baseline json file on every run - this was causing a bug where after parsing, if it had made things worse, the next run would still use those RawPeople objects to create a new baseline

### CODE REVIEW

**Review by VirginiaDooley — APPROVED** [review]

**Comment by VirginiaDooley** [comment]
I have `New raw people count: 279` after running the delete, download, test process.

**Comment by michaeljcollinsuk** [comment]
> I have `New raw people count: 279` after running the delete, download, test process. I also wonder if we should tally the number of 'No changes' and 'Error attempting...' to have a better overall picture of what's happening with each edit. I think just basing improvements on increases in raw people is starting to not be enough as it's possible we are hitting errors on a SOPN that was previously fine while newly parsing one that previously hit an error.

Yeah I also got 279 when deleting and re-downloading. I think I had some objects still handing round from when I had run with `stream` but just checking this now to make sure that it is consistent as 279.

Also I was thinking the same, need more visibility on what is being parsed other than the number. One way to do this is to go and check the `sopn_baseline.json` file that gets created if the number goes up to make sure it hasn't created a load of bad objects. But I was also thinking about adding some more outputs in the shell for quick visibility, just looking at that now

**Comment by VirginiaDooley** [comment]
This PR solves the parsing failure for https://candidates.democracyclub.org.uk/elections/local.devon.broadclyst.2021-05-06/

**Comment by michaeljcollinsuk** [comment]
> This PR solves the parsing failure for https://candidates.democracyclub.org.uk/elections/local.devon.broadclyst.2021-05-06/

Did you come across this one from an existing issue?

**Comment by michaeljcollinsuk** [comment]
Example of the output from the increase from 248 to 279:
```
Old RawPeople count: 248
gla.c.brent-and-harrow.2021-05-06 increased from 0 to 5 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/gla.c.brent-and-harrow.2021-05-06/sopn/.
{'name': 'Anton Georgiou', 'party_id': 'PP90'}
{'name': 'Krupesh Hirani', 'party_id': 'joint-party:53-119'}
{'name': 'Ian Jeffrey Price', 'party_id': 'PP7931', 'description_id': 549}
{'name': 'Molly Irene Samuel-Leport', 'party_id': 'PP52', 'description_id': 1710}
{'name': 'Emma Jane Wallace', 'party_id': 'PP63'}
local.allerdale.aspatria.by.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.allerdale.aspatria.by.2021-05-06/sopn/.
{'name': 'Glenn Christian Doncaster', 'party_id': 'PP11382'}
{'name': 'Billy Miskelly', 'party_id': 'PP53'}
{'name': 'Kevin Thurlow', 'party_id': 'ynmp-party:2'}
{'name': 'Lucy Sian Winter', 'party_id': 'PP52', 'description_id': 1710}
local.allerdale.christchurch.by.2021-05-06 increased from 0 to 5 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.allerdale.christchurch.by.2021-05-06/sopn/.
{'name': 'Eric William Atkinson', 'party_id': 'PP6661'}
{'name': 'Stephen Christopher Barnes', 'party_id': 'PP90'}
{'name': 'Russ Cockburn', 'party_id': 'ynmp-party:2'}
{'name': 'Alan Kennon', 'party_id': 'PP52', 'description_id': 1710}
{'name': 'Helen Tucker', 'party_id': 'PP53'}
local.allerdale.ellen-gilcrux.by.2021-05-06 increased from 0 to 5 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.allerdale.ellen-gilcrux.by.2021-05-06/sopn/.
{'name': 'Scott Andrew James Blagg', 'party_id': 'ynmp-party:2'}
{'name': 'Patrick Gorrill', 'party_id': 'PP52', 'description_id': 1710}
{'name': 'Martin Trevor Mundahl Harris', 'party_id': 'PP53'}
{'name': 'Margrit Wendy Scott', 'party_id': 'PP90'}
{'name': 'Dianne Estelle Standen', 'party_id': 'PP63', 'description_id': 1224}
local.allerdale.seaton-northside.by.2021-05-06 increased from 0 to 5 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.allerdale.seaton-northside.by.2021-05-06/sopn/.
{'name': 'Aileen Elizabeth Brown', 'party_id': 'ynmp-party:2'}
{'name': 'Beth Dixon', 'party_id': 'PP53'}
{'name': 'Alistair John Grey', 'party_id': 'PP63', 'description_id': 1224}
{'name': 'Andrew Murray', 'party_id': 'PP90'}
{'name': 'Colin Sharpe', 'party_id': 'PP52', 'description_id': 1710}
local.allerdale.st-johns.by.2021-05-06 increased from 0 to 6 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.allerdale.st-johns.by.2021-05-06/sopn/.
{'name': 'Margaret Bennett', 'party_id': 'PP90'}
{'name': 'George Campbell', 'party_id': 'ynmp-party:2'}
{'name': 'Andrew Eccles', 'party_id': 'ynmp-party:2'}
{'name': 'Debbie Barbara Garton', 'party_id': 'PP52', 'description_id': 1710}
{'name': 'Antony David McGuckin', 'party_id': 'PP53'}
{'name': 'Alison Heather Parker', 'party_id': 'PP63', 'description_id': 1224}
local.amber-valley.alfreton.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.alfreton.2021-05-06/sopn/.
{'name': 'Marlene Bennett', 'party_id': 'PP53'}
{'name': 'Christian Dale', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Paul Robin Gibbons', 'party_id': 'PP90'}
{'name': 'Leo Francis Swarvett', 'party_id': 'PP63'}
local.amber-valley.belper-central.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.belper-central.2021-05-06/sopn/.
{'name': 'Paul Clarence Beardmore', 'party_id': 'PP90'}
{'name': 'Steve Kennedy', 'party_id': 'PP63'}
{'name': 'John Nelson', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Maurice Richard Neville', 'party_id': 'joint-party:53-119'}
local.amber-valley.belper-north.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.belper-north.2021-05-06/sopn/.
{'name': 'Ben Rupert Edward Bellamy', 'party_id': 'joint-party:53-119'}
{'name': 'James Major John Brooks', 'party_id': 'PP63'}
{'name': 'Mark Edward Robertson', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Richard Alan Salmon', 'party_id': 'PP90'}
local.amber-valley.codnor-and-waingroves.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.codnor-and-waingroves.2021-05-06/sopn/.
{'name': 'Jackie Blackett', 'party_id': 'PP63'}
{'name': 'Chris Emmas-Williams', 'party_id': 'joint-party:53-119'}
{'name': 'Jeremy Quentin Miles', 'party_id': 'PP90'}
{'name': 'Lorna Tassi', 'party_id': 'PP52', 'description_id': 1709}
local.amber-valley.heage-and-ambergate.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.heage-and-ambergate.2021-05-06/sopn/.
{'name': 'Colin Bailey', 'party_id': 'PP53'}
{'name': 'Tony Harper', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'David Martin Hatchett', 'party_id': 'PP63'}
{'name': 'Jan Thompson', 'party_id': 'PP90'}
local.amber-valley.heanor-and-loscoe.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.heanor-and-loscoe.2021-05-06/sopn/.
{'name': 'Hilary Ann Fender', 'party_id': 'PP63'}
{'name': 'Kieran James Denbygh Hill', 'party_id': 'PP53'}
{'name': 'Steve Radford', 'party_id': 'PP90'}
{'name': 'Dale Christopher Wright', 'party_id': 'PP52', 'description_id': 1709}
local.amber-valley.heanor-east.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.heanor-east.2021-05-06/sopn/.
{'name': 'Mark Anthony Burrell', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Cathie Hallsworth', 'party_id': 'PP63'}
{'name': 'Jerry Marler', 'party_id': 'PP90'}
{'name': 'Janet Irene Ward', 'party_id': 'PP53'}
local.amber-valley.heanor-west.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.heanor-west.2021-05-06/sopn/.
{'name': 'Celia Mary Cox', 'party_id': 'joint-party:53-119'}
{'name': 'Tina Pritchard', 'party_id': 'PP63'}
{'name': 'Barbara Woodcock Radford', 'party_id': 'PP90'}
{'name': 'Jackie Stones', 'party_id': 'PP52', 'description_id': 1709}
local.amber-valley.ironville-and-riddings.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.ironville-and-riddings.2021-05-06/sopn/.
{'name': 'Jack Watson Brown', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Rachael Mary Hatchett', 'party_id': 'PP63'}
{'name': 'Kate Mary Kift', 'party_id': 'PP90'}
{'name': 'Paul Christopher Wardle', 'party_id': 'PP53'}
local.amber-valley.kilburn-denby-and-holbrook.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.kilburn-denby-and-holbrook.2021-05-06/sopn/.
{'name': 'Chris Gent', 'party_id': 'PP90'}
{'name': 'Paul Alexander Hillier', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Matt McGuinness', 'party_id': 'PP63'}
{'name': 'Keith Lisle Venables', 'party_id': 'joint-party:53-119'}
local.amber-valley.langley-mill-and-aldercar.2021-05-06 increased from 0 to 5 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.langley-mill-and-aldercar.2021-05-06/sopn/.
{'name': 'Steven Bower', 'party_id': 'PP53'}
{'name': 'Sam Goodrum', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Joanna Karpasea', 'party_id': 'PP90'}
{'name': 'Timothy Knowles', 'party_id': 'PP2707'}
{'name': 'Julie Christine Wozniczka', 'party_id': 'PP63'}
local.amber-valley.ripley.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.ripley.2021-05-06/sopn/.
{'name': 'Tony Holmes', 'party_id': 'joint-party:53-119'}
{'name': 'Matt Murray', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Richard William Smeeton', 'party_id': 'PP90'}
{'name': 'Jamie Alexander Walls', 'party_id': 'PP63'}
local.amber-valley.ripley-and-marehay.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.ripley-and-marehay.2021-05-06/sopn/.
{'name': 'Michael Peter Bedford', 'party_id': 'PP63'}
{'name': 'Paul Arthur Gillians', 'party_id': 'PP90'}
{'name': 'Trevor Spencer', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Mick Wilson', 'party_id': 'PP53'}
local.amber-valley.somercotes.2021-05-06 increased from 0 to 7 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.amber-valley.somercotes.2021-05-06/sopn/.
{'name': 'Steve Elliott', 'party_id': 'PP63'}
{'name': 'John McCabe', 'party_id': 'PP53'}
{'name': 'Paul Price', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Philip Sanders Rose', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Katie Louise Simpson', 'party_id': 'PP53'}
{'name': 'Paul Slater', 'party_id': 'PP90'}
{'name': 'Kate Smith', 'party_id': 'PP90'}
local.barnet.edgware.by.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.barnet.edgware.by.2021-05-06/sopn/.
{'name': 'Bilbow', 'party_id': 'PP53'}
{'name': 'Nick Mearing-Smith', 'party_id': 'PP52', 'description_id': 1710}
{'name': 'Sam Murray', 'party_id': 'PP63', 'description_id': 1224}
{'name': 'Tichborne Roger Martin', 'party_id': 'PP90'}
local.broxbourne.broxbourne-and-hoddesdon-south.2021-05-06 increased from 0 to 4 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.broxbourne-and-hoddesdon-south.2021-05-06/sopn/.
{'name': 'Helen Jane Austen', 'party_id': 'PP63', 'description_id': 1222}
{'name': 'Kirstie Jane Mounsteven de Rivaz', 'party_id': 'PP90'}
{'name': 'David William Holliday', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Jean Terry Legg', 'party_id': 'PP53'}
local.broxbourne.cheshunt-north.2021-05-06 increased from 0 to 3 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.cheshunt-north.2021-05-06/sopn/.
{'name': 'Ian Martin Charles Dust', 'party_id': 'PP53'}
{'name': 'Kostas Inchenko', 'party_id': 'PP90'}
{'name': 'Linda Joy Russell', 'party_id': 'PP52', 'description_id': 1709}
local.broxbourne.cheshunt-south-and-theobalds.2021-05-06 increased from 0 to 3 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.cheshunt-south-and-theobalds.2021-05-06/sopn/.
{'name': 'Carol Ann Crump', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Andreas Kyriacos Georgiou', 'party_id': 'PP53'}
{'name': 'Cody McCormick', 'party_id': 'ynmp-party:2'}
local.broxbourne.flamstead-end.2021-05-06 increased from 0 to 2 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.flamstead-end.2021-05-06/sopn/.
{'name': 'Dee Hart', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Roy William Wareham', 'party_id': 'PP53'}
local.broxbourne.goffs-oak.2021-05-06 increased from 0 to 3 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.goffs-oak.2021-05-06/sopn/.
{'name': 'Fabio Bonfante', 'party_id': 'PP90'}
{'name': 'Pierce Alexander Connolly', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Jo Goldsmith', 'party_id': 'PP53'}
local.broxbourne.hoddesdon-north.2021-05-06 increased from 0 to 3 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.hoddesdon-north.2021-05-06/sopn/.
{'name': 'Steven Keith Basing', 'party_id': 'PP53'}
{'name': 'Keith Martin Brown', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Peter Kemp', 'party_id': 'PP90'}
local.broxbourne.hoddesdon-town-and-rye-park.2021-05-06 increased from 0 to 3 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.hoddesdon-town-and-rye-park.2021-05-06/sopn/.
{'name': 'Ken Ayling', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Timothy David Peter Vizer', 'party_id': 'PP90'}
{'name': 'George Robert Kenneth Williams', 'party_id': 'PP53'}
local.broxbourne.rosedale-and-bury-green.2021-05-06 increased from 0 to 3 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.rosedale-and-bury-green.2021-05-06/sopn/.
{'name': 'Peter Leonard Chorley', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Jayne Marie Cripps', 'party_id': 'PP53'}
{'name': 'Deb Highfield', 'party_id': 'PP90'}
local.broxbourne.waltham-cross.2021-05-06 increased from 0 to 2 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.waltham-cross.2021-05-06/sopn/.
{'name': 'Patsy Spears', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Sean Michael Waters', 'party_id': 'PP53'}
local.broxbourne.wormley-and-turnford.2021-05-06 increased from 0 to 3 parsed people.
Check the SOPN at https://candidates.democracyclub.org.uk/elections/local.broxbourne.wormley-and-turnford.2021-05-06/sopn/.
{'name': 'Lewis Christopher Cocking', 'party_id': 'PP52', 'description_id': 1709}
{'name': 'Beverly Madeline Susan Hanshaw', 'party_id': 'PP53'}
{'name': 'Lisa Ann Naylor', 'party_id': 'PP90'}
New total RawPeople count: 279
```

**Comment by VirginiaDooley** [comment]
And other fixed! https://candidates.democracyclub.org.uk/elections/local.derbyshire.derwent-valley.2021-05-06/sopn/

**Pull request merged**
