### PR TITLE
Order ballot lock suggestions alphabetically

### PR DESCRIPTION
**Pull request by VirginiaDooley**
Closes https://github.com/DemocracyClub/yournextrepresentative/issues/100

### CODE REVIEW

**Comment by symroe** [comment]
There's a tricky bit of UI thinking to do with this one...


The reason it's ordered randomly is because when we're in the middle of the SOPN process we might have ~5 people at a time checking this page. If all 5 see the exact same list, at the same time, then they might end up just duplicating each other's work.

If they all see a random list, then the chance of duplicate work becomes much less, especially when we have a lot of suggestions.

It would be nice to find a way to show a random _election_, but still order any ballots within that election. E.g so that person A might see all the ballots (with suggestions) for election A, person B sees all the ballots for election B, etc.

I don't know if we can do `order_by("?", "ballot")` or something like that - but either way I think we should consider preventing duplicate work

**Comment by symroe** [comment]
Another idea to consider is for each ballot to have some JS that calls the API to check if it's been locked or the suggestion removed. It could poll every few seconds and disable the buttons and show a message when the lock suggestion is no longer valid

**Comment by VirginiaDooley** [comment]
@symroe Tricky indeed. But both good ideas for solutions. I could start with the `order_by("?", "ballot")` idea (which, as you said, isn't fail safe) and exhaust that option before trying JS/API call. I also wonder if introducing a concurrent editing library would be overkill? https://readthedocs.org/projects/django-concurrency/

**Comment by michaeljcollinsuk** [comment]
> There's a tricky bit of UI thinking to do with this one...
> 
> The reason it's ordered randomly is because when we're in the middle of the SOPN process we might have ~5 people at a time checking this page. If all 5 see the exact same list, at the same time, then they might end up just duplicating each other's work.
> 
> If they all see a random list, then the chance of duplicate work becomes much less, especially when we have a lot of suggestions.
> 
> It would be nice to find a way to show a random _election_, but still order any ballots within that election. E.g so that person A might see all the ballots (with suggestions) for election A, person B sees all the ballots for election B, etc.
> 
> I don't know if we can do `order_by("?", "ballot")` or something like that - but either way I think we should consider preventing duplicate work

I was having a think about how we could do this and it seemed like we want to get a random `Election` and then return ballots associated with that election? But also ensuring that the election that is returned actually has some suggested locks/SOPN etc. This is what I came up with:

```
num_lock_suggestions = Count('ballot', filter=Q(ballot__suggestedpostlock__isnull=False))
num_unlocked = Count('ballot', filter=Q(ballot__candidates_locked=False))
num_with_official_document = Count('ballot', filter=Q(ballot__officialdocument__isnull=False))
elections = Election.objects.annotate(
    num_lock_suggestions=num_lock_suggestions
).annotate(
    num_unlocked=num_unlocked
).annotate(
    num_with_official_document=num_with_official_document
)

election = elections.filter(
    num_lock_suggestions__gte=1, 
    num_unlocked__gte=1, 
    num_with_official_document__gte=1,
).order_by('?').first()
```

Then you use the random Election object to grab the ballots with the existing logic:
```
qs = (
    election.ballot_set.filter(candidates_locked=False)
    .exclude(suggestedpostlock=None)
    .exclude(officialdocument=None)
    .select_related("election", "post")
    .prefetch_related(
        "officialdocument_set",
        models.Prefetch(
            "suggestedpostlock_set",
            SuggestedPostLock.objects.select_related("user"),
        ),
        models.Prefetch(
            "membership_set",
            Membership.objects.select_related(
                "person", "party"
            ).prefetch_related("person__other_names"),
        ),
    )
)

qs = qs.exclude(suggestedpostlock__user=self.request.user)
return qs
```
I only have this locally at the moment, but if this is on the right track I can commit and expand on it.

**Comment by michaeljcollinsuk** [comment]
One thing I did think about the above approach is that it will reduce the 'randomness' somewhat, as there are fewer "Election" objects

**Comment by symroe** [comment]
I think this is a decent approach :+1: 

A couple of points:

1. I think we can simplify the first query, as we can only make a suggest lock if the ballot has a SOPN, and we delete the suggested lock objects once we lock the ballot. This means that I think we can just use `num_lock_suggestions__gte=1`
2. The randomness matters less after the work you did on ballot hashes. Still, it would be good to know if a ballot has been changed quicker - maybe we look at some really lightweight JS polling on that page?

**Comment by symroe** [comment]
For polling I'm thinking:

1. Get the ballot hashes from the page (JS loop over all `data-ballot-hash` values)
2. For each, request the API filtering by the hash and unlocked. If 200, nothing has changed, if 404, it's invalid
3. if it's invalid, show a message and disable the form

We could run this logic every 10 seconds or so and I think it would catch most problems

**Pull request merged**
