### PR TITLE
Feature/flag locked ballot name edits

### PR DESCRIPTION
**Pull request by VirginiaDooley**
https://trello.com/c/JgXXgbyA/2926-filter-name-change-edits-on-locked-ballots

### CODE REVIEW

**Comment by symroe** [comment]
Thanks for this!

I see what you're doing with the new logged action, but I don't think we need to add it, especially not for every edit to the name.

Can you do something a bit more like `CandidateStatementEditDecider` and look at the version diff? You should be able to query the person model for the locked ballots, something like `person.memberships.filter(ballot__election__current=True, ballot__locked=True).exists()`

And this should all be possible inside `LockedBallotNameEdits`

**Comment by VirginiaDooley** [comment]
> 



> Thanks for this!
> 
> I see what you're doing with the new logged action, but I don't think we need to add it, especially not for every edit to the name.
> 
> Can you do something a bit more like `CandidateStatementEditDecider` and look at the version diff? You should be able to query the person model for the locked ballots, something like `person.memberships.filter(ballot__election__current=True, ballot__locked=True).exists()`
> 
> And this should all be possible inside `LockedBallotNameEdits`

Then how is that different to `CandidateCurrentNameDecider`?

**Comment by symroe** [comment]
> Then how is that different to `CandidateCurrentNameDecider`?

You know, it's not at all :facepalm: I didn't know we had that, and the button is right there on the review page. Thanks for spotting, and sorry you ended up doing this duplicate work :(

**Comment by VirginiaDooley** [comment]
> > Then how is that different to `CandidateCurrentNameDecider`?
> 
> You know, it's not at all 🤦 I didn't know we had that, and the button is right there on the review page. Thanks for spotting, and sorry you ended up doing this duplicate work :(

No worries! The comment specified 'by a bot' but I couldn't see any code that specified the type of user so I thought maybe that was the difference.

**Pull request closed without merging**
