### PR TITLE
Data explorer interface and CSV export

### PR DESCRIPTION
**Pull request by symroe**
This PR is intended as a spike to figure out some ideas, it's not really designed to be a fully working, or well formed. It might turn in to something real, but that's not the intent just yet.

It's an attempt at solving a few problems:

1. CSV output. This is currently done in a fairly slow and CPU intensive management command that creates an ever growing set of CSVs, one per date, one per election, and one of all memberships. (all CSVs have a row per membership, with person values duplicated).

2. Stats and custom reports in the frontend. This doesn't really exist at the moment, but we have some user demand for querying the data in a few ways:

  * People with / without an identifier of type (all people without an email, for an election I care about)
  * Number of candidates per election
  * other stats
  
At the moment all this is done by querying the raw data model, with some complex joins. Because the queries are expensive, we've found ways of caching them, either using Django's cache, down stream caches or things like writing to S3 for the CSVs.

This spike iterates on the cache idea, but uses a materialized view in Postgres to manage the "cache", and an unmanaged model in Django to interact with it.

It has a few advantages:

* Postgres is very good at optimising the query, and creating the view takes less than 3 seconds on my laptop

* Updating the content of the view is as simple as running `REFRESH MATERIALIZED VIEW` and takes a little less time than creating the view. It's possible to run this in a transaction.

* Indexes on the view make almost any query I can imagine take under 50ms. This includes a regex text search of the ballot paper and an `ORDER BY` on date.

* On the Django side, the unmanaged model can still use the ORMs features, so the FKs work as expected. This allows creating custom exports easier, although some of the performance boost is lost as a JOIN is required.

* The SQL to make the view is long and complex, but it's a single point of complexity, with all the surrounding code being much easier to write and think about

* The view means that it's the the SQL's job to convert the data in to a useful format. This makes changing the underlying data schema a little easier. This is important to note as we might make some changes to this soon – to introduce voting systems, for example.

I wanted to work on this to see how hard / bad it would be. I know I've not thought through this fully, but so far my impressions are that it's worth investing more time in, and might allow us to make the "data query interface" thing we've talked about in the past without a lot of custom faffing about – an interface built on a single table is much easier to make / take off the shelf than one that requires a lot of complex queries. 

Notes on the query:

One row per membership, with election, ballot, person information, more or less as the CSV is right now. Some fields excluded, but mostly because they're not useful to learn about the problem. 

The worst part was the `crosstab` part, pivoting the `PersonIdentifier` table to columns. I think the approach of writing it out in SQL makes some sense, and also takes away some of the problems about having dynamic fields. The view would have to be dropped and remade for a new column to show up, but that's ok.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205277313772964

### CODE REVIEW

**Comment by symroe** [comment]
This pull request **introduces 4 alerts** and **fixes 10** when merging 10c28db6a267d8fbc52d7ee99447019fb4554134 into 42ccda973d172c635155afd84186cd6c3574cb18 - [view on LGTM.com](https://lgtm.com/projects/g/DemocracyClub/yournextrepresentative/rev/pr-89e8ad125bac29c91a9656cf353b1f39b158946b)

**new alerts:**

* 2 for Conflicting attributes in base classes
* 2 for Unused import

**fixed alerts:**

* 9 for Wrong number of arguments in a class instantiation
* 1 for Wrong number of arguments in a call

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by symroe** [comment]
Since writing this I've thought that the `PersonIdentifier` fields might be better as a JSONField with an index on – this would allow for the case of having, e.g. TheyWorkForYou URLs blank for 99% of rows, and generally allow for changing those fields without altering columns all the time.

I'm not sure how to magic rows in to JSON in SQL, but I'm sure there's a way

**Comment by symroe** [comment]
I've pushed a change to the view that converts the identifiers to JSON.

This has a few advantages, and maybe some disadvantages…

The new table has a single "identifiers" column, with IDs in the format:

```json
{
    "linkedin_url": "https://uk.linkedin.com/in/abdulla-abby-jan-dharamsey-39018237",
    "twitter_username": "UK999ers"
}

```

## Advantages

* It's now a narrower column, and adding a new field means we don't have to add a new column. Adding `n` fields to a single person is more manageable

* The format is a single object with `k->v`, but it's easy to convert this to `k->[v0, v1, …]`, either for all fields or just some fields. This would require dropping the unique constraint on `person, value_type` and changing the interface (and more), but the underlying data structure is simple to understand, and better than creating columns for `email0, email1` or whatever

* Queries are still fast (enough) on this amount of data, without indexes:  
```sql
SELECT person_id, identifiers->'email' as email, identifiers->'twitter_username' as twitter 
FROM materialized_memberships 
WHERE (identifiers->'email') IS NOT NULL
AND (identifiers->'twitter_username') IS NULL
```
takes ~65ms on my laptop and returns ~9,000 rows

* The Django site of things gets easier too, with no need to define each column as a field on the unmanaged model. The above SQL is expressed in Django as `MaterializedMemberships.objects.filter(identifiers__email__isnull=True, identifiers__twitter_username__isnull=False)`

## Disadvantages

Well, maybe lots of things ;) It could be the whole thing is a silly idea!

But, the thing that's worse about using JSON here is that it's going to slow down the CSV creation in some way that I don't yet understand. I reckon using SQL to turn the JSON in to columns will be the quickest, but if we want to use python then it might use a lot of memory to convert it to CSV. Will need to test this.

**Comment by mhl** [comment]
FWIW, I think using a materialized view for this is a great idea :+1:

**Comment by symroe** [comment]
I spent some time refactoring this and polishing it up.

I think it's in a reasonable place, but I suggest we soft-launch it to see what people think.

The only place this new system is exposed in the PR is in the links to the CSV files. I've done this because they're sort of broken at the moment anyway.

@VirginiaDooley and @Bekabyx I'd appreciate it if you could test locally. 

I'll need to add some docs and I have a couple more things to add, but the main content is here.

**Comment by symroe** [comment]
For some numbers, this produces the full ~16MB CSV file form scratch in just over a second total. about half of that is transfer time (locally), so the CSV generation work is about 500ms.

**Comment by symroe** [comment]
Fixes #1507

**Comment by symroe** [comment]
Refs #1294

**Pull request merged**
