### PR TITLE
Reduce time and errors on photo uploads

### PR DESCRIPTION
**Pull request by VirginiaDooley**
Ref https://app.asana.com/0/1204880927741389/1207101641238151/f
These changes are aimed at speeding up the photo upload process. 
- removes the rotate functionality from the save method on the upload form
- moves the rotation to a renamed management command that processes moderation queue images, including running facial recognition
- runs the job every minute
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207101641238151

### CODE REVIEW

**Review by pmk01 — APPROVED** [review]

**Comment by symroe** [comment]
I don't think this is going to solve anything, and in fact I think it will case more problems. 

We can upload images larger than 1mb, and there are many uploads that are larger than this in the system (most, in fact, so I think this basically disables uploads).

The problem is somewhere around converting the image to png or rotating it. It might be a simple timeout in gunicorn. I don't know the details, but the solution will look like doing that work outside of the main upload process I expect.

**Comment by symroe** [comment]
TBH I don't think this is important enough to work on today. We can ask people to email us if something breaks, I guess?

**Comment by VirginiaDooley** [comment]
> I don't think this is going to solve anything, and in fact I think it will case more problems.
> 
> We can upload images larger than 1mb, and there are many uploads that are larger than this in the system (most, in fact, so I think this basically disables uploads).
> 
> The problem is somewhere around converting the image to png or rotating it. It might be a simple timeout in gunicorn. I don't know the details, but the solution will look like doing that work outside of the main upload process I expect.

Ok, understood about 1MB, but we aren't limiting upload size at all. I'll look further into the 

> I don't think this is going to solve anything, and in fact I think it will case more problems.
> 
> We can upload images larger than 1mb, and there are many uploads that are larger than this in the system (most, in fact, so I think this basically disables uploads).
> 
> The problem is somewhere around converting the image to png or rotating it. It might be a simple timeout in gunicorn. I don't know the details, but the solution will look like doing that work outside of the main upload process I expect.

At the moment, we aren't capping the photo size for uploads at all, so even if just for storage costs, maybe we want to add a max that seems reasonable.

After further testing, you're right - the `rotate_image` step is taking way too long, even when it's not needed. I see if there is a way to speed it up when rotation isn't needed.

**Review by symroe — COMMENTED** [review]
I think we need to move to a slightly different model here, with a slightly bigger refactor.

1. Let's just accept images on upload with no work in the backend at all (e.g just save the raw image)
2. Rename `moderation_queue_detect_faces_in_queued_images` to `moderation_queue_process_queued_images` 
3. Make that management command call AWS like it does at the moment, but call `exif_transpose` on the image first.
4. Update the cron to run this command every minute. It'll be a no-op if there aren't any images in the queue.

**Review by symroe — APPROVED** [review]

**Pull request merged**
