### PR TITLE
Don't ask people to fill in pointless forms.

### PR DESCRIPTION
**Pull request by davidmiller**

### CODE REVIEW

**Comment by symroe** [comment]
This is not a pointless form, as it gets emailed to the uploading user.

It might be worth removing the form it if there isn't an uploading user (e.g a bot added the photo)

**Comment by jf1** [comment]
Those lines shouldn't be deleted but could be wrapped in: if imagesource is not twitterbot then...

**Comment by symroe** [comment]
Yep, I reckon `{% if username %}` wrapped around the form would do it.

**Comment by davidmiller** [comment]
@symroe sounds good. Would vote for that feature - closing this PR as it sounds like you'd want to test it as not Github-based-development.

**Pull request closed without merging**
