### PR TITLE
README: small tidyup

### PR DESCRIPTION
**Pull request by jpluscplusm**
This adds a missing word to some prose in the README as a litmus test of my ability to PR changes into YNR.

### CODE REVIEW

**Comment by jpluscplusm** [comment]
Thanks for approving this, @symroe :-)

What's the happy path for PRs in this repo: who merges them - the committer, or someone else?

If it's the committer, do they have to orchestrate that with anyone else?
If it's someone else, what prompts that to happen?

**Comment by symroe** [comment]
We generally merge the PRs we've authored. This is on the understanding that you're best placed to deal with any deployment failures or bugs in the code you've written.

No need to plan merges with others most of the time, there are (instinct based) exceptions for a) large DB changes and b) busy pre-election days.

**Comment by jpluscplusm** [comment]
@symroe I'm not sure why the CI run on merge failed (https://github.com/DemocracyClub/yournextrepresentative/runs/33245465537) as I can't see the logs in CircleCI.

Because the production site is still live and working, and this change was so "obviously" not-service-affecting, I'm going to leave this as-is and not dig further just yet.

**Comment by symroe** [comment]
image

The deploy job to 0 seconds and CircleCi gives me an error when I try to load the job page. 

I think this is a CircleCI issue and it's not letting me re-run the job. 

We have deployed recently, so I'd expect everything to be working. I'm happy to ignore this failure and see what happens on the next deploy.

**Pull request merged**
