### PR TITLE
Add username to pagination link for recent changes

### PR DESCRIPTION
**Pull request by VirginiaDooley**
Closes https://github.com/DemocracyClub/yournextrepresentative/issues/1188

I've added the username to the previous/next links on pagination for the recent changes template.

### CODE REVIEW

**Comment by symroe** [comment]
Looking at this made me think that we'd solved this problem elsewhere, but I couldn't remember where.

The reason it's a little tricky is that there are a few cases:

1. No `username` param exists - this won't break anything but will add an extra `username=` param to the URL - this looks a little odd
2. We want to combine different filters - imagine we want to filter on `flagged_type=needs_review_due_to_high_profile` too.

Looking around a little, I found that we do have an unused bit of code in the `uk_results` app: [`get_query`](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/uk_results/templatetags/get_query.py#L10). It looks like this hasn't been used for a while, as it's still using python 2 `unicode` calls. I think it would be good to clean this up for python 3 and start using it here.

It basically means it will modify whatever params are there, replacing the ones specified:

`{% query_string  request.GET page=actions.next_page_number %}`

**Comment by VirginiaDooley** [comment]
> {% query_string request.GET page=actions.next_page_number %}



> Looking at this made me think that we'd solved this problem elsewhere, but I couldn't remember where.
> 
> The reason it's a little tricky is that there are a few cases:
> 
> 1. No `username` param exists - this won't break anything but will add an extra `username=` param to the URL - this looks a little odd
> 2. We want to combine different filters - imagine we want to filter on `flagged_type=needs_review_due_to_high_profile` too.
> 
> Looking around a little, I found that we do have an unused bit of code in the `uk_results` app: [`get_query`](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/uk_results/templatetags/get_query.py#L10). It looks like this hasn't been used for a while, as it's still using python 2 `unicode` calls. I think it would be good to clean this up for python 3 and start using it here.

Will do. 
> 
> It basically means it will modify whatever params are there, replacing the ones specified:
> 
> `{% query_string request.GET page=actions.next_page_number %}`

Would this also work? 

```
 {% if actions.has_next %}
       <a href="{{ actions.number.paginator.next_page_number }}">next</a>
 {% endif %}
```

**Comment by symroe** [comment]
> Would this also work? We use paginator in combo with the current page.

I've not tested this - but I suspect this will just be the number, not the other params?

**Comment by VirginiaDooley** [comment]
> > Would this also work? We use paginator in combo with the current page.
> 
> I've not tested this - but I suspect this will just be the number, not the other params?

It does work in two cases, but I've made the changes as you suggested.

**Review by symroe — APPROVED** [review]

**Pull request merged**
