### PR TITLE
Add whitespace around source URL in review feed

### PR DESCRIPTION
**Pull request by andylolz**
Fixing this would make the source links clickable in slack!

### CODE REVIEW

**Comment by mhl** [comment]
A tiny thing - you've put the reasoning for this "Fixing this would make the source links clickable in slack!" in the pull request message, but not the commit message. If you could amend it so that the the "why?" is in the commit message too, that'd be great.

**Comment by andylolz** [comment]
Oh… I did that on purpose, because how it’s displayed in slack doesn’t relate to the feed itself.

**Comment by andylolz** [comment]
Okay – updated with a hopefully better / more generic explanation :)

**Comment by mhl** [comment]
:+1: Great, thanks - looks good to me

**Comment by mhl** [comment]
Oops, I shouldn't have approved this before Travis came back - it needs an update in the tests too. I'll make a new PR for that though. Sorry...

**Comment by andylolz** [comment]
Oh I did a new PR for that… My bad :(

**Pull request merged**
