### PR TITLE
Hide SOPN stuff; bump candidate search up

### PR DESCRIPTION
**Pull request by andylolz**
I.e.
screen shot 2017-04-21 at 11 31 48

### CODE REVIEW

**Comment by JoeMitchell** [comment]
This is great! I approve whole-heartedly.

**Comment by symroe** [comment]
Ace, thanks!

I'd still like the locals verification progress bar – we still want people to verify them and it feels wrong to ignore them on the home page.

I think I'll merge this, and then add that progress bar – what do you think?

**Comment by andylolz** [comment]
> I'd still like the locals verification progress bar – we still want people to verify them and it feels wrong to ignore them on the home page.

Only admins can verify though, right? So that is only relevant for admins? And for admins, it’s duplicated in the ‘post lock suggestions’ counter in the nav?

**Comment by JoeMitchell** [comment]
I'm with Andy on this one — the progress bar isn't helping us smash through
verifying, cos only a handful of people can. A new user told me they were
confused by the verification message and so gave up on doing anything
else... :(

**Comment by symroe** [comment]
Yes, good point both, I'd forgotten that you have to have the permission to lock posts.

**Pull request merged**
