### PR TITLE
Better elections pages

### PR DESCRIPTION
**Pull request by symroe**
When reviewing I reckon e1ae6050d142e7c62dbc31ded94cd25d73e835ea can mostly be ignored as it's a lot of duplication. Related: let's not duplicate this as much in future if we can.

## Turns this
screenshot 2018-03-23 17 20 04

## In to this
screenshot 2018-03-23 17 19 45

Thoughts on this welcome. I think it's more useful to see the info in one place, but I know some people like having a short list.

@JoeMitchell, reckons?

### CODE REVIEW

**Comment by chris48s** [comment]
It definitely looks more aesthetically pleasing.. Here are some fairly unstructured comments/questions:

* What's the user journey we're optimising for here? I feel like I could provide better feedback if I had a clearer idea of "what is the job that is currently hard which this makes easier" and "how do people currently use this page?" Are we trying to make it this more friendly for data consumers, or quicker to work out where there is data entry that needs to be done?

* It seems like one of the things we're losing here that you have in the first view is a one screenfull overview that tells me which wards are locked and which ones are unlocked (from a data entry perspective, this is broadly the information I care about here, I think). Is there somewhere else I can get that, should that also be summarised here?

* If we're optimising for data entry, do you think there is value in providing some metric of.. profile-completeness next to the candidates (e.g: icons like on WhoCIVF, a % of fields filled in) maybe if we're going to do that it belongs on `/post`. Perhaps that is a separate issue..

**Comment by JoeMitchell** [comment]
I agree with Chris!

**Comment by symroe** [comment]
We chatted about this one a call. I basically said that we don't know a lot about how anyone uses any page. The reason for this change were:

1. It's hard to see if we have any candidates for an election at the moment. You have to dip in to each post page.

2. A lot of people like to gather data for their area. We see this in spreadsheets, so I thought that this view might act as a sort of alternative to them. This is why the CSV download is there too.

3. The party bulk add feature can be linked to from this page

4. The sort of unrelated change to adding `post_election` to `MembershipExtra` will be useful in loads of other ways.

**Comment by chris48s** [comment]
OK. Lets accept that data model change is useful and the template changes are relatively easy to iterate based on feedback. Deploying so we can some feedback is probably more useful than pontificating about it :)

> It's hard to see if we have any candidates for an election at the moment. You have to dip in to each post page.

:+1: good point. One alternative option we might want to consider if this turns out to be a bit long is that we could provide an overview of this by showing a number of candidates rather than listing them verbatim, like we do with Orinoco:

screenshot at 2018-03-29 13 51 26

**Comment by jf1** [comment]
I feel there's so much value in making it "quicker to work out where there is data entry that needs to be done", and there is definitely "value in providing some metric of profile-completeness next to..."

Could there be a table aka live dashboard on the c.dc home page with columns for:
Area Posts Seats Candidates WithContactInfo WithStatements

Initial view could be of just one row for "UK" which could be expanded to show "National elections" and "Local elections" with each row displaying the appropriate totals in every cell. Then national could be expanded to show HoC, SP, WA, NIA while locals could have some grouping (eg by the 7 EU Regions then each CA/County) then LAs then wards.

WithContactInfo should have a value of 1 if there's any type of contact info eg email, twitter, facebook, website, etc.

Any chance of getting something like this running before April 10?

**Comment by symroe** [comment]
@jf1 Yep, I'm looking at the home page CTAs this afternoon and over the weekend :)

**Comment by jf1** [comment]
Nice one, thanks @symroe. Hope you're considering a spec along those lines. Shout up if you'd like any further input.

**Comment by symroe** [comment]
I'll do a PR here and ping you – it'll have screenshots and everything! :)

**Pull request merged**
